### ISSUE TITLE
Client secret should be optional?

### ISSUE THREAD

**Issue by jeremija** [jaredhanson/passport-oauth2-client-password#11]
The [OAuth2 RFC](https://tools.ietf.org/html/rfc6749#section-2.3.1) states that `client_secret` is required, however below it says:

> The client MAY omit the parameter if the client secret is an empty string.

Currently the first lines in `Strategy#authenticate()` look like this:

```javascript
if (!req.body || (!req.body['client_id']) || (!req.body['client_secret'])) {
  return this.fail();
}
```

The authentication won't work even if the user passes an empty string as `client_secret`, because in JavaScript `!''` evaluates to `true`. For example, this could be a case if the client was an installable app where the client secret can not really stay secret.

Is there any reason to keep ` || (!req.body['client_secret'])` part in the if clause?

Thanks in advance.

**Comment by jaredhanson** [comment]
If you want to support public clients (those that don't have a secret), then there is effectively no authentication of such clients.  That has security implications, that should be understood, but it is allowed per the spec.

The recommended approach here is to allow anonymous clients by using [passport-anonymous](https://github.com/jaredhanson/passport-anonymous) as a strategy:

```
passport.authenticate(['oauth2-client-password', 'anonymous'], ...)
```

**Comment by jeremija** [comment]
Hi Jared,

Thank you for your reply. You're right - embedding `client_id` and `client_secret` in a mobile app effectively makes no difference than using it as an anonymous client, because anybody could just decompile the app and extract client credentials.

But the anonymous strategy would not verify whether or not the `client_id` exists at all. I'd still like to be able to identify the mobile client, even though it would not be able to keep credentials confidential, so I was thinking about going with a blank `client_secret` for such clients. [This](https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified#password) was pretty much my train of thought.

> To use the password grant type, simply make a POST request like the following:
```
POST https://api.oauth2server.com/token
    grant_type=password&
    username=USERNAME&
    password=PASSWORD&
    client_id=CLIENT_ID
```
> The server replies with an access token in the same format as the other grant types.

> Note, the client secret is not included here under the assumption that most of the use cases for password grants will be mobile or desktop apps, where the secret cannot be protected.

Maybe the `client_secret` should still be embedded within the mobile app, I was just worried it would provide a false sense of security.

**Comment by jaredhanson** [comment]
You can still verify the client_id exists, but its important to note you are still not authenticating anything.

Do something like:

```
function loadPublicClient(req, res, next) {
   if (!req.user) { // "user" is the authenticated client, if using a non-public client
      client.findById(req.body.client_id, function(err, client) {
        // ...
        next();
      }
   }
}
```

If all you do is check that the client ID exists, its still important to note that the client can put *any* ID there (including that of a different client).  It's impossible to verify this, and thus it is unauthenticatable which is why this strategy fails in such a case.

**Comment by jeremija** [comment]
Thanks, I understand. I'd probably also want to verify if that specific client is actually a public client (for example, has a blank password).

Perhaps it's easier to just embed the `client_secret` within the mobile app and just use the regular way. It's just that the secret is not a real secret in that case, and that's what should be pointed out.
