### ISSUE TITLE
Support public clients

### ISSUE THREAD

**Issue by MattTannahill** [jaredhanson/passport-oauth2-client-password#8]
https://tools.ietf.org/html/rfc6749#section-4.1.3

Public clients do not have client secrets.  Therefore, a client secret should not be required in the body.
https://github.com/jaredhanson/passport-oauth2-client-password/blob/master/lib/strategy.js#L38

**Comment by jaredhanson** [comment]
Public clients can be accepted by using `anonymous` authentication:

```
passport.authenticate(['basic', 'oauth2-client-password', 'anonymous'], { session: false });
```

The strategy is provided by [passport-anonymous](https://github.com/jaredhanson/passport-anonymous)
